name: Auto Merge Pull Requests

on:
  pull_request:
    branches:
      - main  
    types:
      - opened
      - synchronize  
      - reopened

jobs:
  auto-merge:
    runs-on: ubuntu-latest

    permissions:
      pull-requests: write
      contents: write  

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Verify PR Author
        run: |
          if [ "${{ github.event.pull_request.user.login }}" != "krishkumar84" ]; then
            echo "PR not created by krishkumar84. Exiting."
            exit 0
          fi

      - name: Auto Merge Pull Request
        uses: peter-evans/merge-pull-request@v2
        with:
          pull-request: ${{ github.event.pull_request.number }}
          merge-method: squash  
          commit-title: "Auto-merge PR #${{ github.event.pull_request.number }}"
          commit-message: |
            Automatically merged by workflow.
