name: Deploy trainees-portal

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    name: Build and Deploy Next.js App
    runs-on: ubuntu-latest

    env:
      APP_NAME: trainees-portal
      VPS_USER: ubuntu
      VPS_HOST: 13.200.185.99
      VPS_PATH: /home/ubuntu/trainees-portal

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Install Dependencies
      run: npm install

    - name: Build Next.js App
      run: npm run build

    - name: Deploy to VPS
      uses: appleboy/ssh-action@v0.1.8
      with:
        host: ${{ env.VPS_HOST }}
        username: ${{ env.VPS_USER }}
        key: ${{ secrets.VPS_SSH_PRIVATE_KEY }}
        script: |
          cd ${{ env.VPS_PATH }}
          git pull origin main

          npm install

          npm run build

          pm2 stop ${{ env.APP_NAME }} || true
          pm2 start npm --name ${{ env.APP_NAME }} -- start
          
          pm2 save
