name: Deploy Next.js App

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    name: Build, Push, and Deploy
    runs-on: ubuntu-latest

    env:
      APP_NAME: trainees-portal
      IMAGE_NAME: iharshyadav/trainees-portal
      VPS_USER: ubuntu
      VPS_HOST: 13.200.185.99
      VPS_PATH: /home/ubuntu/trainees-portal
      CONTAINER_NAME: trainees-portal

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Install Dependencies
      run: npm install

    - name: Build Next.js App
      run: npm run build

    - name: Set up Docker
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and Push Docker Image
      run: |
        docker build -t $IMAGE_NAME .
        docker push $IMAGE_NAME

    - name: Deploy to VPS
      uses: appleboy/ssh-action@v0.5.3
      with:
        host: $VPS_HOST
        username: $VPS_USER
        key: ${{ secrets.VPS_SSH_PRIVATE_KEY }}
        script: |
          docker pull $IMAGE_NAME
          
          docker stop $CONTAINER_NAME || true
          docker rm $CONTAINER_NAME || true
          
          docker run -d \
            --name $CONTAINER_NAME \
            -p 80:3000 \
            --restart always \
            $IMAGE_NAME
